CREATE DATABASE PRO131_EF
GO
USE PRO131_EF
GO
CREATE TABLE [USERS] (
  [ID] UNIQUEIDENTIFIER NOT NULL DEFAULT newsequentialid(),
  [USERNAME] VARCHAR(255) NULL,
  [EMAIL] VARCHAR(255) NULL,
  [PASSWORD] VARCHAR(255) NULL,
  [PHONE_NUMBER] VARCHAR(255) NULL,
  [ADDRESS] VARCHAR(255) NULL,
  
  [CREATED_TIME] DATETIME NULL,
  [CREATED_BY] UNIQUEIDENTIFIER NULL,
  
  [DELETED] BIT NULL DEFAULT 0,
  [DELETED_TIME] DATETIME NULL,
  [DELETED_BY] UNIQUEIDENTIFIER NULL,
  
  [MODIFIED_TIME] DATETIME NULL,
  [MODIFIED_BY] UNIQUEIDENTIFIER NULL,

  [STATUS] TINYINT NULL,

  [ROLE_ID] UNIQUEIDENTIFIER NULL,
  PRIMARY KEY ([ID]),
);

CREATE TABLE [PRODUCTS] (
  [ID] UNIQUEIDENTIFIER NOT NULL DEFAULT newsequentialid(),
  [PRODUCT_NAME] VARCHAR(255) NULL,

  [DISCOUNT_ID] UNIQUEIDENTIFIER NULL,

  [PRICE] DECIMAL NULL,
  [DESCRIPTION] VARCHAR(255) NULL,
  [QUANTITY] INT NULL,
  [WARRANTY] FLOAT NULL,
  [DISPLAY] FLOAT NULL,
  [RAM] INT NULL,
  [ROM] INT NULL,

  [CREATED_TIME] DATETIME NULL,
  [CREATED_BY] UNIQUEIDENTIFIER NULL,

  [DELETED] BIT NULL DEFAULT 0,
  [DELETED_TIME] DATETIME NULL,
  [DELETED_BY] UNIQUEIDENTIFIER NULL,

  [MODIFIED_TIME] DATETIME NULL,
  [MODIFIED_BY] UNIQUEIDENTIFIER NULL,

  [STATUS] TINYINT NULL DEFAULT 1,
  PRIMARY KEY ([ID]),
  --FOREIGN KEY ([DISCOUNT_ID]) REFERENCES [DISCOUNTS] ([ID]),
  --FOREIGN KEY ([PRODUCT_CATEGORY]) REFERENCES [PRODUCT_CATEGORIES] ([ID]),
  --FOREIGN KEY ([BRAND]) REFERENCES [BRANDS] ([ID])
);

CREATE TABLE [PRODUCT_DETAIL] 
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),

	[PRODUCT_ID] UNIQUEIDENTIFIER NULL,
	
	[CODE] VARCHAR(255) NULL,
	[RAM] INT NULL,
	[DISPLAY] FLOAT NULL,
	[CHIP] VARCHAR(255) NULL,
	[CAMERA] VARCHAR(255) NULL,
	[MEMORY] VARCHAR(255) NULL,
	[PIN] FLOAT NULL,
	[COLOR] VARCHAR(100) NULL,
	[URL_IMAGE] VARCHAR(255) NULL,
	[OPERATING_SYSTEM]	VARCHAR(255) NULL,
	
	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,

	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,

	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,
	
	PRIMARY KEY ([ID]),
);

CREATE TABLE [BILL] 
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	
	[CUSTOMER_ID] UNIQUEIDENTIFIER NULL,
	[NAME_CUSTOMER] NVARCHAR(255) NULL,	
	[STATUS] TINYINT NULL DEFAULT 1,
	[TOTAL_PRICE] DECIMAL NULL , 
	
	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,

	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,

	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,
	
	PRIMARY KEY ([ID]),
);

CREATE TABLE [BILL_DETAIL]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	
	[PRODUCT_ID] UNIQUEIDENTIFIER NULL,
	[BILL_ID] UNIQUEIDENTIFIER NULL,
	[QUANTITY] INT NULL,
	[PRICE] DECIMAL NULL,
	[ADDRESS] NVARCHAR(255) NULL,

	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,
  
	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,
  
	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,


	
);
CREATE TABLE [CART]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	
	[USER_ID] UNIQUEIDENTIFIER NULL,

	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,
  
	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,
  
	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,

	PRIMARY KEY (ID),
);
CREATE TABLE [CART_PRODUCT]
(
	[CART_ID] UNIQUEIDENTIFIER NOT NULL,
	[PRODUCT_ID] UNIQUEIDENTIFIER NOT NULL,
	[QUANTITY] FLOAT NULL,

	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,
  
	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,
  
	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,

	PRIMARY KEY (CART_ID, PRODUCT_ID),
);
CREATE TABLE [CUSTOMER]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	
	[CUSTOMER_TYPE_ID] UNIQUEIDENTIFIER NULL,
	[USER_ID] UNIQUEIDENTIFIER NULL,
	[NAME] NVARCHAR(255) NULL,
	[PHONE_NUMBER] TEXT NULL,
	[EMAIL] VARCHAR(255) NULL,
	[ADDRESS] NVARCHAR(255) NULL,
	[POINT] INT NULL DEFAULT 0,

	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,
  
	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,
  
	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,

	PRIMARY KEY(ID)

);
CREATE TABLE [CUSTOMER_TYPE]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[NAME] NVARCHAR(255) NULL,
	[DESCRIPTION] NVARCHAR(255) NULL,
	
	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,
  
	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,
  
	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,

	PRIMARY KEY(ID)

);
CREATE TABLE [FACILITY]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[NAME] NVARCHAR(255) NULL,
	[PHONE_NUMBER] TEXT NULL,
	[EMAIL] NVARCHAR(255) NULL,
	[ADDRESS] NVARCHAR(255) NULL,
	
	[CREATED_TIME] DATETIME NULL,
    [CREATED_BY] UNIQUEIDENTIFIER NULL,
    
    [DELETED] BIT NULL DEFAULT 0,
    [DELETED_TIME] DATETIME NULL,
    [DELETED_BY] UNIQUEIDENTIFIER NULL,
    
    [MODIFIED_TIME] DATETIME NULL,
    [MODIFIED_BY] UNIQUEIDENTIFIER NULL,
    
    [STATUS] TINYINT NULL,

	PRIMARY KEY(ID)


);
CREATE TABLE [SUPPLIER] 
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[EMPLOYEE_ID] UNIQUEIDENTIFIER NULL,
	[NAME] NVARCHAR(255) NULL,
	[PHONE_NUMBER] TEXT NULL,
	[EMAIL] NVARCHAR(255) NULL,
	[ADDRESS] NVARCHAR(255) NULL,
	
	[CREATED_TIME] DATETIME NULL,
    [CREATED_BY] UNIQUEIDENTIFIER NULL,
    
    [DELETED] BIT NULL DEFAULT 0,
    [DELETED_TIME] DATETIME NULL,
    [DELETED_BY] UNIQUEIDENTIFIER NULL,
    
    [MODIFIED_TIME] DATETIME NULL,
    [MODIFIED_BY] UNIQUEIDENTIFIER NULL,
    
    [STATUS] TINYINT NULL,

	PRIMARY KEY(ID)

);

CREATE TABLE [IMPORT_HISTORY]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[PRODUCT_ID] UNIQUEIDENTIFIER NULL,
	[SUPPLIER_ID] UNIQUEIDENTIFIER NULL,
	[PRODUCT_NAME] NVARCHAR(255) NULL,
	[QUANTITY] INT NULL DEFAULT 0,
	[PRICE] DECIMAL NULL DEFAULT 0,
	
	[CREATED_TIME] DATETIME NULL,
    [CREATED_BY] UNIQUEIDENTIFIER NULL,
    
    [DELETED] BIT NULL DEFAULT 0,
    [DELETED_TIME] DATETIME NULL,
    [DELETED_BY] UNIQUEIDENTIFIER NULL,
    
    [MODIFIED_TIME] DATETIME NULL,
    [MODIFIED_BY] UNIQUEIDENTIFIER NULL,
    
    [STATUS] TINYINT NULL,

	PRIMARY KEY(ID)


);
CREATE TABLE [EMPLOYEE]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[FACILITY_ID] UNIQUEIDENTIFIER NULL,
	[USER_ID] UNIQUEIDENTIFIER NULL,
	[NAME] NVARCHAR(255) NULL,
	[PHONE_NUMBER] TEXT NULL,
	[EMAIL] VARCHAR(255) NULL,
	[ADDRESS] NVARCHAR(255) NULL,


	[CREATED_TIME] DATETIME NULL,
    [CREATED_BY] UNIQUEIDENTIFIER NULL,
    
    [DELETED] BIT NULL DEFAULT 0,
    [DELETED_TIME] DATETIME NULL,
    [DELETED_BY] UNIQUEIDENTIFIER NULL,
    
    [MODIFIED_TIME] DATETIME NULL,
    [MODIFIED_BY] UNIQUEIDENTIFIER NULL,
    
    [STATUS] TINYINT NULL,

	PRIMARY KEY(ID)


);
CREATE TABLE [ROLES]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[NAME] NVARCHAR(255) NULL,
	[DESCRIPTION] NVARCHAR(255) NULL,
	
	[CREATED_TIME] DATETIME NULL,
	[CREATED_BY] UNIQUEIDENTIFIER NULL,
  
	[DELETED] BIT NULL DEFAULT 0,
	[DELETED_TIME] DATETIME NULL,
	[DELETED_BY] UNIQUEIDENTIFIER NULL,
  
	[MODIFIED_TIME] DATETIME NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NULL,

	PRIMARY KEY (ID)
);
CREATE TABLE [DISCOUNT] 
(
	
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[NAME] NVARCHAR(255) NULL,
	[DISCOUNT] INT NULL,
	[DESCRIPTION] NVARCHAR(255) NULL,

	[CREATED_TIME] DATETIME NULL,
    [CREATED_BY] UNIQUEIDENTIFIER NULL,
    
    [DELETED] BIT NULL DEFAULT 0,
    [DELETED_TIME] DATETIME NULL,
    [DELETED_BY] UNIQUEIDENTIFIER NULL,
    
    [MODIFIED_TIME] DATETIME NULL,
    [MODIFIED_BY] UNIQUEIDENTIFIER NULL,
    
    [STATUS] TINYINT NULL,

	PRIMARY KEY (ID)
);
-- PRODUCTS
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_DISCOUNT_ID 
FOREIGN KEY ([DISCOUNT_ID])
REFERENCES DISCOUNT(ID)
ON UPDATE CASCADE;
--PRODUCT DETAIL
ALTER TABLE [PRODUCT_DETAIL]
ADD CONSTRAINT FK_PD_PRODUCTS_ID 
FOREIGN KEY ([PRODUCT_ID])
REFERENCES PRODUCTS(ID)
ON UPDATE CASCADE;
--BILL
ALTER TABLE [BILL]
ADD CONSTRAINT FK_BILL_CUSTOMER_ID 
FOREIGN KEY ([CUSTOMER_ID])
REFERENCES CUSTOMER(ID)
ON UPDATE CASCADE;
--BILL DETAIL
ALTER TABLE [BILL_DETAIL]
ADD CONSTRAINT FK_BD_PRODUCTS_ID 
FOREIGN KEY ([PRODUCT_ID])
REFERENCES PRODUCTS(ID)
ON UPDATE CASCADE;
-----------------------
ALTER TABLE [BILL_DETAIL]
ADD CONSTRAINT FK_BD_BILL_ID 
FOREIGN KEY ([BILL_ID])
REFERENCES BILL(ID)
ON UPDATE CASCADE;
--CART
ALTER TABLE [CART]
ADD CONSTRAINT FK_CART_USER_ID 
FOREIGN KEY ([USER_ID])
REFERENCES [USERS](ID)
ON UPDATE CASCADE;
--CART_PRODUCT
ALTER TABLE [CART_PRODUCT]
ADD CONSTRAINT FK_PK1_ID 
FOREIGN KEY ([CART_ID])
REFERENCES [CART](ID)
ON UPDATE CASCADE;
-------------------------
ALTER TABLE [CART_PRODUCT]
ADD CONSTRAINT FK_PK2_ID 
FOREIGN KEY ([PRODUCT_ID])
REFERENCES [PRODUCTS](ID)
ON UPDATE CASCADE;
--CUSTOMER
ALTER TABLE [CUSTOMER]
ADD CONSTRAINT FK_CUSTOMER_USER_ID 
FOREIGN KEY ([USER_ID])
REFERENCES [USERS](ID)
ON UPDATE CASCADE;
---------------------------------------
ALTER TABLE [CUSTOMER]
ADD CONSTRAINT FK_CUSTOMER_CT_ID 
FOREIGN KEY ([CUSTOMER_TYPE_ID])
REFERENCES [CUSTOMER_TYPE](ID)
ON UPDATE CASCADE;
--SUPPLIER
ALTER TABLE [SUPPLIER]
ADD CONSTRAINT FK_SUPPLIER_EMPLOYEE_ID 
FOREIGN KEY ([EMPLOYEE_ID])
REFERENCES [EMPLOYEE](ID)
ON UPDATE CASCADE;
--IMPORT_HISTORY
ALTER TABLE [IMPORT_HISTORY]
ADD CONSTRAINT FK_IH_PRODUCTS_ID 
FOREIGN KEY ([PRODUCT_ID])
REFERENCES [PRODUCTS](ID)
ON UPDATE CASCADE;
------------------------
ALTER TABLE [IMPORT_HISTORY]
ADD CONSTRAINT FK_IH_SUPPLIER_ID 
FOREIGN KEY ([SUPPLIER_ID])
REFERENCES [SUPPLIER](ID)
ON UPDATE CASCADE;
--EMPLOYEE
ALTER TABLE [EMPLOYEE]
ADD CONSTRAINT FK_EMPLOYEE_FACILITY_ID 
FOREIGN KEY ([FACILITY_ID])
REFERENCES [FACILITY](ID)
ON UPDATE CASCADE;
--------------------------------------
ALTER TABLE [EMPLOYEE]
ADD CONSTRAINT FK_EMPLOYEE_USERS_ID 
FOREIGN KEY ([USER_ID])
REFERENCES [USERS](ID)
ON UPDATE CASCADE;

--USERS
ALTER TABLE [USERS]
ADD CONSTRAINT FK_USERS_ROLES_ID 
FOREIGN KEY ([ROLE_ID])
REFERENCES [ROLES](ID)
ON UPDATE CASCADE;

GO 
INSERT INTO ROLES (NAME, DESCRIPTION, CREATED_TIME, CREATED_BY, DELETED, DELETED_TIME, DELETED_BY, MODIFIED_TIME, MODIFIED_BY)
VALUES ('ADMIN', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL),
       ('CUSTOMER', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL);
GO
INSERT INTO [PRODUCTS] ([PRODUCT_NAME], [PRICE], [DESCRIPTION], [QUANTITY], [WARRANTY], [DISPLAY], [RAM], [ROM], [CREATED_TIME], [STATUS])
VALUES
('Iphone X', 10.00, 'Description 1', 100, 1.0, 5.5, 4, 64, GETDATE(), 1),
('Iphone 11', 20.00, 'Description 2', 200, 2.0, 6.0, 8, 128, GETDATE(), 1),
('Iphone 11 Pro', 30.00, 'Description 3', 300, 3.0, 6.5, 16, 256, GETDATE(), 1),
('Iphone 11 ProMax', 40.00, 'Description 4', 400, 4.0, 6.5, 32, 512, GETDATE(), 1),
('Iphone 13', 50.00, 'Description 5', 500, 5.0, 6.5, 64, 1024, GETDATE(), 1);
GO
INSERT INTO [PRODUCT_DETAIL] ([PRODUCT_ID], [CODE], [RAM], [DISPLAY], [CHIP], [CAMERA], [MEMORY], [PIN], [COLOR], [URL_IMAGE], [OPERATING_SYSTEM], [CREATED_TIME])
VALUES
('3D808CC1-85F6-EE11-BCA0-103D1C86EA3D', 'Code1', 4, 5.5, 'Chip1', 'Camera1', 'Memory1', 3000, 'Black', 'url_image1', 'OS1', GETDATE()),
('3E808CC1-85F6-EE11-BCA0-103D1C86EA3D', 'Code2', 8, 6.0, 'Chip2', 'Camera2', 'Memory2', 3500, 'White', 'url_image2', 'OS2', GETDATE()),
('3F808CC1-85F6-EE11-BCA0-103D1C86EA3D', 'Code3', 16, 6.5, 'Chip3', 'Camera3', 'Memory3', 4000, 'Blue', 'url_image3', 'OS3', GETDATE()),
('40808CC1-85F6-EE11-BCA0-103D1C86EA3D', 'Code4', 32, 7.0, 'Chip4', 'Camera4', 'Memory4', 4500, 'Red', 'url_image4', 'OS4', GETDATE()),
('41808CC1-85F6-EE11-BCA0-103D1C86EA3D', 'Code5', 64, 7.5, 'Chip5', 'Camera5', 'Memory5', 5000, 'Green', 'url_image5', 'OS5', GETDATE());
GO

update PRODUCT_DETAIL set URL_IMAGE = 'C:\Users\Admin\OneDrive\Máy tính\ShopNowFinal\Source Code\Image\Products\Iphone11Pro.jpg'
--USE master
--DROP DATABASE PRO131_EF
